# -*- coding: utf-8 -*-
"""video_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/136wBnJ4Ou0Zj25pLdQkhIZeR8ggnA-OM
"""

import cv2
def read_video(video_path):
  cap=cv2.VideoCapture(video_path)
  frames=[]
  while True:
    ret,frame=cap.read()
    if ret:
      frames.append(frame)
    else:
      break
  cap.release()
  return frames

def save_video(output_video_frames,output_video_path):
  fourcc=cv2.VideoWriter_fourcc(*'XVID')
  out=cv2.VideoWriter(output_video_path,fourcc,24,(output_video_frames[0].shape[1],output_video_frames[0].shape[0]))
  for frame in output_video_frames:
    out.write(frame)
  out.release()